title: Sirius Game Studio
description: Indie game developer.
image: /assets/images/site-image.jpg
keywords: Indie, Game Developer, Game Studio
author: Blake Sirius Anacleto

permalink: "news/:title"

tagline: We Form Games Out Of Nebulas.
favicon-url: /assets/images/favicon.png
logo: /assets/images/logo.png

facebook-username: RoopkothaStudio
youtube-username: roopkothastudio6651
twitter-username: RoopkothaStudio

# Build settings

plugins:
  - jekyll-feed

collections:
  games:
    output: true